# Compile Stage
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /build
EXPOSE 80
EXPOSE 443

COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /release

# Build Image 
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS final
WORKDIR /app
COPY --from=build /release .

ENTRYPOINT ["dotnet", "ghost.dll"]
EXPOSE 80