name: rant
description: Read, Write, Hear, Shout, See

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: 0.2.6
  scoped: 1.9.0
  wakelock: 0.1.3+4
  permission_handler: ^4.0.0
  cupertino_icons: ^0.1.2
  rxdart: 0.23.1
  chopper: 3.0.1+1
  uuid: 2.0.4

  font_awesome_flutter: ^8.7.0

#dependency_overrides:
#  scoped:
#    path: "../../scoped"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.4
  chopper_generator: 3.0.3

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - images/a_dot_ham.jpeg
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: fonts/SFPro/sf-pro-text-regular.ttf
        - asset: fonts/SFPro/sf-pro-text-bold.ttf
          weight: 700
        - asset: fonts/SFPro/sf-pro-text-heavy.ttf
          weight: 900
        - asset: fonts/SFPro/sf-pro-text-light.ttf
          weight: 300
        - asset: fonts/SFPro/sf-pro-text-medium.ttf
          weight: 500
        - asset: fonts/SFPro/sf-pro-text-semibold.ttf
          weight: 600
    - family: Helvetica Neue
      fonts:
        - asset: fonts/HelveticaNeue/HelveticaNeue-Thin.ttf
          weight: 100
        - asset: fonts/HelveticaNeue/HelveticaNeue-UltraLight.ttf
          weight: 200
        - asset: fonts/HelveticaNeue/HelveticaNeue-Light.ttf
          weight: 300
        - asset: fonts/HelveticaNeue/HelveticaNeue.ttf
          weight: 400
        - asset: fonts/HelveticaNeue/HelveticaNeue-Medium.ttf
          weight: 500
        - asset: fonts/HelveticaNeue/HelveticaNeue-Bold.ttf
          weight: 700