apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - rage.swipelab.co
      secretName: rage-swipelab-co
  rules:
    - host: rage.swipelab.co
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ghost-cluster-ip-service
              servicePort: 80